<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\2015DayOne\2015DayOne.csproj" />
      <ProjectReference Include="..\Common\Common.csproj" />
      <ProjectReference Include="..\ElvesLookElvesSay\ElvesLookElvesSay.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="input.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="ElevatorInput.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
